package com.group7.eduscrum_awards.dto;

import com.group7.eduscrum_awards.model.Degree;
import lombok.NoArgsConstructor;
import lombok.Getter;
import lombok.Setter;

/**
 * Data Transfer Object (DTO) for the {@link Degree} entity.
 *
 * This simple DTO is used to expose degree information across the service
 * and REST layers without exposing the full JPA entity. It contains only the
 * fields required by the API or client.
 *
 */
@NoArgsConstructor
@Getter
@Setter
public class DegreeDTO {

    /** Database primary key — generated by the persistence provider. */
    private Long id;
    
    /** Degree name. */
    private String name;

    /**
     * Create a DTO from the given entity.
     *
     * @param degree the source {@link Degree} entity (must not be null)
     */
    public DegreeDTO(Degree degree) {
        this.id = degree.getId();
        this.name = degree.getName();
    }
}