# Application Properties for EduScrum Awards Application
spring.application.name=eduscrum-awards
server.port=8080

# Activate the 'dev' profile by default
spring.profiles.active=dev

# JPA and Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect