package com.group7.eduscrum_awards.model;

import jakarta.persistence.*;
import lombok.NoArgsConstructor;
import lombok.Getter;
import lombok.Setter;

/** Entity representing an academic degree (e.g. "Bachelor", "Master"). */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "degrees")
public class Degree {
    
    /** Database primary key — generated by the persistence provider. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Degree name. */
    @Column(name = "name", nullable = false, unique = true, length = 100)
    private String name;

    /**
     * Convenience constructor to create a Degree with a name.
     *
     * @param name the degree name (not null)
     */
    public Degree(String name) {
        this.name = name;
    }

    /**
     * Equality is based on the identifier when it is set.
     * Two transient instances (with null id) are considered different.
     *
     * @param o object to compare
     * @return true if both objects are the same or have the same non-null id
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Degree degree = (Degree) o;
        return id != null && id.equals(degree.id);
    }

    /** Uses the class hash when id is null to avoid collisions for transient instances. */
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
