package com.group7.eduscrum_awards.model;

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;
import lombok.NoArgsConstructor;
import lombok.Getter;
import lombok.Setter;

/** Entity representing an academic degree (e.g. "Bachelor", "Master"). */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "degrees")
public class Degree {
    
    /** Database primary key — generated by the persistence provider. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Degree name. */
    @Column(name = "name", nullable = false, unique = true, length = 100)
    private String name;

    /**
     * The set of courses that belong to this degree.
     * This is the "One" side of a One-to-Many relationship.
     * mappedBy = "degree": Instructs JPA to look for the 'degree'
     * field in the 'Course' class to locate the foreign-key configuration.
     * cascade = CascadeType.ALL: If a Degree is deleted, all associated Course entities will also be deleted.
     * orphanRemoval = true: Removing a Course from this set will delete it from the database.
     */
    @OneToMany(
        mappedBy = "degree",
        cascade = CascadeType.ALL,
        orphanRemoval = true,
        fetch = FetchType.LAZY
    )
    private Set<Course> courses = new HashSet<>();

    /**
     * Convenience constructor to create a Degree with a name.
     *
     * @param name the degree name (not null)
     */
    public Degree(String name) {
        this.name = name;
    }

    /**
     * Adds a course to this degree and sets up the bidirectional relationship.
     * @param course the course to add
     */
    public void addCourse(Course course) {
        this.courses.add(course);
        course.setDegree(this); // Keeps both sides in sync
    }

    /**
     * Removes a course from this degree and breaks the bidirectional relationship.
     * @param course the course to remove
     */
    public void removeCourse(Course course) {
        this.courses.remove(course);
        course.setDegree(null); // Breaks the association
    }

    /**
     * Equality is based on the identifier when it is set.
     * Two transient instances (with null id) are considered different.
     *
     * @param o object to compare
     * @return true if both objects are the same or have the same non-null id
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Degree degree = (Degree) o;
        return id != null && id.equals(degree.id);
    }

    /** Uses the class hash when id is null to avoid collisions for transient instances. */
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
